version: "3.4"
services:
  web:
    image: brendanramirez11/tcmg-lab6
    ports:
      - "80:80"
    networks:
      - webnet
  redis:
    image: redis
    networks:
      - webnet
networks:
  webnet: