name: Docker Image Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Image Build
      run: docker build . --file project8docker --tag brendanramirez11/project8:$(date +%s)
